name: Translations diff check
description: "a GH Action to check difference in translation files"
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
branding:
  icon: 'git-pull-request'
  color: green
runs:
  using: 'node12'
  main: 'index.js'