name: Pull Request Approved
description: "A GitHub Action to handle when PRs have been approved"
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  slack-webhook-url:
    description: 'OPTIONAL, only for slack features. The SLACK_WEBHOOK_URL secret, required if sending slack messages'
  bot-name:
    description: 'The name that the bot should use when posting to slack'
  icon_emoji:
    description: 'The emoji the slack bot will use as its avatar'
  slack-channel:
    description: 'Required if not using `github-slack-mapping`. The channel in which to report that changes were requested.'
  github-slack-mapping:
    description: "Required if not using `slack-channel`. A JSON encoded string with of { <github-user-id>: <slack-user-id> } for all members of your org."
branding:
  icon: "git-pull-request"
  color: green
runs:
  using: "node12"
  main: "index.js"